"use client";

import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { SectionHeader, StatusBadge } from "@/components/study-ui";
import { useCallback, useState } from "react";
import { archiveCard, archiveDeck, flashcardError, getCards, getDecks, updateCard, type Card, type CardStatus, type Deck } from "@/services/flashcards";
import { getSubjects } from "@/services/subjects";
import { useResourceTimezone as useFlashcardTimezone } from "@/features/resources/use-resource-timezone";
import { LoadNotice, Pagination, QuizDialog, useQuizLoad } from "@/features/quizzes/shared";
import { CardEditor } from "./card-editor";
import { DeckEditor } from "./deck-editor";
import { DeckSelector } from "./deck-selector";
import { CardHistory } from "./card-history";
import { flashcardTimestamp } from "./review-state";

export function FlashcardLibrary() {
  const [filters, setFilters] = useState({ q: "", subject_id: "", deck_id: "", status: "active" as CardStatus | "all", offset: 0 });
  const [search, setSearch] = useState("");
  const [deckFilters, setDeckFilters] = useState({ q: "", offset: 0 });
  const [deckSearch, setDeckSearch] = useState("");
  const [editor, setEditor] = useState<Card | "new" | null>(null);
  const [deckEditor, setDeckEditor] = useState<Deck | "new" | null>(null);
  const [history, setHistory] = useState<Card | null>(null);
  const [archive, setArchive] = useState<{ kind: "card"; entity: Card } | { kind: "deck"; entity: Deck } | null>(null);
  const [busy, setBusy] = useState(false);
  const [writeError, setWriteError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const subjects = useQuizLoad(useCallback((signal) => getSubjects(signal), []));
  const cards = useQuizLoad(useCallback(async (signal) => ({ ...(await getCards({ ...filters, limit: 20 }, signal)), filters }), [filters]));
  const decks = useQuizLoad(useCallback(async (signal) => ({ ...(await getDecks({ ...deckFilters, subject_id: filters.subject_id, limit: 20 }, signal)), filters: deckFilters, subject: filters.subject_id }), [deckFilters, filters.subject_id]));
  const { timezone, timezoneNote, timezoneFailed, retryTimezone } = useFlashcardTimezone();
  async function status(card: Card) { setBusy(true); setWriteError(null); setNotice(null); try { await updateCard(card.id, { status: card.status === "active" ? "suspended" : "active" }); setNotice(card.status === "active" ? "Card suspended. It is excluded from recall." : "Card reactivated. Its existing schedule is preserved."); cards.retry(); } catch (failure) { setWriteError(flashcardError(failure)); } finally { setBusy(false); } }
  async function confirmArchive() { if (!archive) return; setBusy(true); setWriteError(null); try { if (archive.kind === "card") await archiveCard(archive.entity.id); else await archiveDeck(archive.entity.id); setNotice(archive.kind === "card" ? "Card archived. Its history is preserved." : "Deck archived. Its cards are detached and their schedules/history are preserved."); setArchive(null); cards.retry(); decks.retry(); } catch (failure) { setWriteError(flashcardError(failure)); } finally { setBusy(false); } }
  return <><PageHeader title="Flashcards" description="Your cards, decks and review history." actions={<><Link className="secondary-button" href="/recall">Open recall</Link><button className="primary-button" onClick={() => setEditor("new")}>New flashcard</button></>} />{notice && <p className="planner-notice" role="status">{notice}</p>}{writeError && !archive && <p className="auth-error" role="alert">{writeError}</p>}
    <form className="resource-filters" onSubmit={(event) => { event.preventDefault(); setFilters({ ...filters, q: search.trim(), offset: 0 }); }}><label className="resource-search">Search cards<input type="search" maxLength={200} value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Subject<select disabled={!subjects.data} value={filters.subject_id} onChange={(event) => { setFilters({ ...filters, subject_id: event.target.value, offset: 0 }); setDeckFilters({ ...deckFilters, offset: 0 }); }}><option value="">All subjects</option>{subjects.data?.map((subject) => <option key={subject.id} value={subject.id}>{subject.code}</option>)}</select></label><DeckSelector value={filters.deck_id} filter change={(deck_id) => setFilters({ ...filters, deck_id, offset: 0 })} /><label>Status<select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value as CardStatus | "all", offset: 0 })}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="archived">Archived</option></select></label><button className="secondary-button">Search</button></form>
    <div className="resource-timezone"><p className="resource-note">{timezoneNote}</p>{timezoneFailed && <button className="secondary-button" onClick={retryTimezone}>Retry timezone</button>}</div><LoadNotice loading={false} error={subjects.error} retry={subjects.retry} /><LoadNotice loading={cards.loading} error={cards.error} retry={cards.retry} />{cards.data && cards.data.filters !== filters && <p className="resource-note">Showing the last loaded cards while filters refresh.</p>}{cards.data && <>{!cards.data.cards.length && <section className="resource-empty"><h2>No cards match this view</h2><p>Create a flashcard or adjust the filters.</p></section>}<ul className="quiz-list">{cards.data.cards.map((card) => <li className="quiz-row flashcard-row" key={card.id}><div className="quiz-row-copy"><strong>{card.front}</strong><span className="flashcard-schedule"><StatusBadge tone={card.status === "active" ? "success" : "neutral"}>{card.status}</StatusBadge> Next review <time dateTime={card.next_review_at}>{flashcardTimestamp(card.next_review_at, timezone)}</time></span><details><summary>View answer</summary><p className="flashcard-text">{card.back}</p>{card.notes && <p className="resource-note flashcard-text">{card.notes}</p>}{card.resource_id && <Link className="quiz-text-link" href={`/library/${card.resource_id}`}>Source{card.source_page ? ` · Page ${card.source_page}` : ""}</Link>}</details></div><div className="resource-actions"><button className="secondary-button" disabled={busy} onClick={() => setEditor(card)}>Edit</button><button className="secondary-button" disabled={busy} onClick={() => setHistory(card)}>History</button><button className="secondary-button" disabled={busy} onClick={() => void status(card)}>{card.status === "active" ? "Suspend" : "Reactivate"}</button>{card.status !== "archived" && <button className="secondary-button" disabled={busy} onClick={() => { setWriteError(null); setArchive({ kind: "card", entity: card }); }}>Archive</button>}</div></li>)}</ul><Pagination offset={cards.data.filters.offset} total={cards.data.total} busy={cards.loading || busy} change={(offset) => setFilters({ ...filters, offset })} /></>}
    <section className="flashcard-decks" aria-labelledby="flashcard-decks-title"><SectionHeader title="Decks" titleId="flashcard-decks-title" detail="Organize related cards without changing their review schedules." actions={<button className="secondary-button" onClick={() => setDeckEditor("new")}>New deck</button>} /><form className="resource-filters" onSubmit={(event) => { event.preventDefault(); setDeckFilters({ q: deckSearch.trim(), offset: 0 }); }}><label className="resource-search">Search decks<input type="search" maxLength={200} value={deckSearch} onChange={(event) => setDeckSearch(event.target.value)} /></label><button className="secondary-button">Search decks</button></form><LoadNotice loading={decks.loading} error={decks.error} retry={decks.retry} />{decks.data && <>{(decks.data.filters !== deckFilters || decks.data.subject !== filters.subject_id) && <p className="resource-note">Showing the last loaded decks while filters refresh.</p>}{!decks.data.decks.length && <section className="resource-empty"><h3>No decks match this view</h3><p>Create a deck to group your study cards, or adjust your search.</p></section>}<ul className="quiz-list">{decks.data.decks.map((deck) => <li className="quiz-row" key={deck.id}><div className="quiz-row-copy"><strong>{deck.title}</strong><span>{deck.subject_id ? subjects.data?.find((subject) => subject.id === deck.subject_id)?.code ?? "Subject linked" : "Any subject"}</span>{deck.description && <span>{deck.description}</span>}</div><div className="resource-actions"><button className="secondary-button" onClick={() => setFilters({ ...filters, deck_id: deck.id, offset: 0 })}>View cards</button><button className="secondary-button" disabled={busy} onClick={() => setDeckEditor(deck)}>Edit</button><button className="secondary-button" disabled={busy} onClick={() => { setWriteError(null); setArchive({ kind: "deck", entity: deck }); }}>Archive</button></div></li>)}</ul><Pagination offset={decks.data.filters.offset} total={decks.data.total} busy={decks.loading || busy} change={(offset) => setDeckFilters({ ...deckFilters, offset })} /></>}</section>
    {editor && <CardEditor card={editor === "new" ? undefined : editor} close={() => setEditor(null)} saved={() => { setNotice("Flashcard saved."); cards.retry(); }} />}{deckEditor && <DeckEditor deck={deckEditor === "new" ? undefined : deckEditor} close={() => setDeckEditor(null)} saved={() => { setNotice("Deck saved."); decks.retry(); }} />}{history && <CardHistory card={history} close={() => setHistory(null)} />}{archive && <QuizDialog title={`Archive ${archive.kind}?`} busy={busy} close={() => setArchive(null)}><p>{archive.kind === "card" ? "This archives the card and excludes it from recall. Review history is kept." : "This archives the deck and detaches its cards. The cards, schedules and review history are kept."}</p>{writeError && <p className="auth-error" role="alert">{writeError}</p>}<div className="planner-dialog-actions"><button className="secondary-button" disabled={busy} onClick={() => setArchive(null)}>Keep {archive.kind}</button><button className="danger-button" disabled={busy} onClick={() => void confirmArchive()}>{busy ? "Archiving…" : `Archive ${archive.kind}`}</button></div></QuizDialog>}
  </>;
}
