import { ProgressMeter, SectionHeader, StatusBadge } from "@/components/study-ui";
import type { Assessment, AssessmentAttempt, Readiness } from "@/services/assessments";
import { assessmentTimestamp } from "./form-state";

const percent = (value: number) => `${new Intl.NumberFormat("en", { maximumFractionDigits: 2 }).format(value)}%`;
export function CoverageView({ assessment }: { assessment: Pick<Assessment, "coverage_subjects" | "coverage_topics" | "topic_count"> }) {
  return <section className="assessment-section" aria-label="Assessment coverage"><SectionHeader title="Coverage" detail={`${assessment.topic_count} covered topics`} />{!assessment.coverage_subjects.length && !assessment.coverage_topics.length ? <p className="resource-note">Coverage has not been selected yet.</p> : <ul className="assessment-coverage-list">{assessment.coverage_subjects.map((subject) => <li key={subject.id}><strong>{subject.code} — {subject.name}</strong>{subject.scope === "all_topics" ? <StatusBadge tone="info">All topics</StatusBadge> : <ul>{assessment.coverage_topics.filter((topic) => topic.subject_id === subject.id).map((topic) => <li key={topic.id}>{topic.code ? `${topic.code} — ` : ""}{topic.title}</li>)}</ul>}</li>)}</ul>}</section>;
}
export function ReadinessView({ readiness: r }: { readiness: Readiness }) {
  return <section className="assessment-section" aria-labelledby="assessment-preparation"><SectionHeader titleId="assessment-preparation" title="Preparation evidence" detail={`Current study activity across ${r.topic_count} covered topics. These components do not predict an assessment result.`} /><dl className="assessment-evidence"><div><dt>Video completion</dt><dd>{r.video_completion_percentage === null ? "No covered videos" : <>{percent(r.video_completion_percentage)} <span>· {r.completed_videos} / {r.total_videos} videos completed</span></>}{r.total_videos > 0 && <ProgressMeter value={r.completed_videos} total={r.total_videos} label="Covered video completion" />}</dd></div><div><dt>Quiz accuracy</dt><dd>{r.quiz_accuracy_percentage === null ? "No graded quiz answers" : <>{percent(r.quiz_accuracy_percentage)} <span>· {r.quiz_correct_answers} / {r.quiz_graded_answers} answers correct</span></>}{r.quiz_graded_answers > 0 && <ProgressMeter value={r.quiz_correct_answers} total={r.quiz_graded_answers} label="Covered quiz accuracy" tone="info" />}</dd></div><div><dt>Flashcard review</dt><dd>{r.reviewed_flashcards} / {r.active_flashcards} active cards reviewed{r.active_flashcards > 0 && <ProgressMeter value={r.reviewed_flashcards} total={r.active_flashcards} label="Covered flashcards reviewed" />}</dd></div><div><dt>Recall due</dt><dd className="assessment-recall-counts"><StatusBadge tone={r.due_flashcards ? "warning" : "neutral"}>{r.due_flashcards} due</StatusBadge><StatusBadge tone={r.overdue_flashcards ? "danger" : "neutral"}>{r.overdue_flashcards} overdue</StatusBadge></dd></div></dl><p className="resource-note">Quiz accuracy includes covered questions from completed quiz attempts, including unanswered questions as incorrect. Repeat attempts count separately. Reviewed does not mean mastered. Due cards include overdue cards.</p><p className="resource-note">As of <time dateTime={r.as_of}>{assessmentTimestamp(r.as_of, r.timezone)}</time> ({r.timezone}). Overdue uses your profile’s local day.</p></section>;
}
export function AttemptHistoryView({ attempts, timezone, archived, edit }: { attempts: AssessmentAttempt[]; timezone: string; archived: boolean; edit: (attempt: AssessmentAttempt) => void }) {
  return !attempts.length ? <div className="assessment-history-empty"><h3>No results recorded yet.</h3>{!archived && <p className="resource-note">Record a result when you have completed an assessment. You can leave its score blank.</p>}</div> : <ul className="assessment-history">{attempts.map((attempt) => <li key={attempt.id}><div className="assessment-history-heading"><div className="assessment-result-score">{attempt.percentage === null ? <StatusBadge>Unscored</StatusBadge> : <><strong>{percent(attempt.percentage)}</strong><span>{attempt.score} / {attempt.max_score}</span></>}</div>{!archived && <button className="secondary-button" type="button" onClick={() => edit(attempt)}>Edit result</button>}</div><p className="resource-note">{attempt.completed_at ? <>Completed <time dateTime={attempt.completed_at}>{assessmentTimestamp(attempt.completed_at, timezone)}</time></> : "Completion time not recorded"}{attempt.started_at && <> · Started {assessmentTimestamp(attempt.started_at, timezone)}</>}</p>{attempt.notes && <p className="assessment-description">{attempt.notes}</p>}<p className="resource-note">Recorded {assessmentTimestamp(attempt.created_at, timezone)} · {timezone}</p></li>)}</ul>;
}
