import type { Assessment, AssessmentAttempt, Readiness } from "@/services/assessments";
import { assessmentTimestamp } from "./form-state";

const percent = (value: number) => `${new Intl.NumberFormat("en", { maximumFractionDigits: 2 }).format(value)}%`;
export function CoverageView({ assessment }: { assessment: Pick<Assessment, "coverage_subjects" | "coverage_topics" | "topic_count"> }) {
  return <section className="assessment-section" aria-label="Assessment coverage"><h2>Coverage</h2><p className="resource-note">{assessment.topic_count} covered topics</p>{!assessment.coverage_subjects.length && !assessment.coverage_topics.length ? <p className="resource-note">Coverage has not been selected yet.</p> : <ul className="assessment-coverage-list">{assessment.coverage_subjects.map((subject) => <li key={subject.id}><strong>{subject.code} — {subject.name}</strong>{subject.scope === "all_topics" ? <p className="resource-note">All topics</p> : <ul>{assessment.coverage_topics.filter((topic) => topic.subject_id === subject.id).map((topic) => <li key={topic.id}>{topic.code ? `${topic.code} — ` : ""}{topic.title}</li>)}</ul>}</li>)}</ul>}</section>;
}
export function ReadinessView({ readiness: r }: { readiness: Readiness }) {
  return <section className="assessment-section" aria-labelledby="assessment-preparation"><h2 id="assessment-preparation">Preparation evidence</h2><p className="resource-note">Current study activity across {r.topic_count} covered topics. These components do not predict an assessment result.</p><dl className="assessment-evidence"><div><dt>Video completion</dt><dd>{r.video_completion_percentage === null ? "No covered videos" : <>{percent(r.video_completion_percentage)} <span>· {r.completed_videos} / {r.total_videos} videos completed</span></>}</dd></div><div><dt>Quiz accuracy</dt><dd>{r.quiz_accuracy_percentage === null ? "No graded quiz answers" : <>{percent(r.quiz_accuracy_percentage)} <span>· {r.quiz_correct_answers} / {r.quiz_graded_answers} answers correct</span></>}</dd></div><div><dt>Flashcard review</dt><dd>{r.reviewed_flashcards} / {r.active_flashcards} active cards reviewed</dd></div><div><dt>Recall due</dt><dd>{r.due_flashcards} due <span>· {r.overdue_flashcards} overdue</span></dd></div></dl><p className="resource-note">Quiz accuracy includes covered questions from completed quiz attempts, including unanswered questions as incorrect. Repeat attempts count separately. Reviewed does not mean mastered. Due cards include overdue cards.</p><p className="resource-note">As of <time dateTime={r.as_of}>{assessmentTimestamp(r.as_of, r.timezone)}</time> ({r.timezone}). Overdue uses your profile’s local day.</p></section>;
}
export function AttemptHistoryView({ attempts, timezone, archived, edit }: { attempts: AssessmentAttempt[]; timezone: string; archived: boolean; edit: (attempt: AssessmentAttempt) => void }) {
  return !attempts.length ? <p className="resource-note">No results recorded yet.</p> : <ul className="assessment-history">{attempts.map((attempt) => <li key={attempt.id}><div className="assessment-history-heading"><strong>{attempt.percentage === null ? "Unscored" : `${attempt.score} / ${attempt.max_score} · ${percent(attempt.percentage)}`}</strong>{!archived && <button className="secondary-button" type="button" onClick={() => edit(attempt)}>Edit result</button>}</div><p className="resource-note">{attempt.completed_at ? <>Completed <time dateTime={attempt.completed_at}>{assessmentTimestamp(attempt.completed_at, timezone)}</time></> : "Completion time not recorded"}{attempt.started_at && <> · Started {assessmentTimestamp(attempt.started_at, timezone)}</>}</p>{attempt.notes && <p className="assessment-description">{attempt.notes}</p>}<p className="resource-note">Recorded {assessmentTimestamp(attempt.created_at, timezone)} · {timezone}</p></li>)}</ul>;
}
