const assert = require("node:assert/strict");
const fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const React = require("react"), { renderToStaticMarkup } = require("react-dom/server"), ts = require("typescript");
const src = path.join(__dirname, "../src"), modules = new Map(), calls = [];
let loadOverrides = null, stateOverrides = null, stateIndex = 0;
class ApiError extends Error { constructor(message, status) { super(message); this.status = status; } }
const api = { ApiError, ...Object.fromEntries(["Get", "Post", "Patch", "Delete"].map((verb) => [`authenticated${verb}`, async (...args) => { calls.push([verb, ...args]); return {}; }])) };
function load(file) {
  if (modules.has(file)) return modules.get(file).exports;
  const module = { exports: {} }; modules.set(file, module);
  function local(name) {
    if (name === "react") return { ...React, useState: (initial) => stateOverrides ? [stateOverrides[stateIndex++], () => {}] : React.useState(initial) };
    if (name === "./api" || name === "@/services/api") return api;
    if (name === "next/link") return { default: ({ children, ...props }) => React.createElement("a", props, children) };
    if (name === "next/navigation") return { useRouter: () => ({ push() {} }) };
    if (name === "@/features/quizzes/shared") { const shared = load(path.join(src, "features/quizzes/shared.tsx")); return { ...shared, useQuizLoad: (...args) => loadOverrides ? { data: null, loading: false, error: null, retry() {}, ...loadOverrides.shift() } : shared.useQuizLoad(...args) }; }
    if (name.startsWith("@/") || name.startsWith(".")) { const base = name.startsWith("@/") ? path.join(src, name.slice(2)) : path.resolve(path.dirname(file), name); return load(fs.existsSync(base + ".tsx") ? base + ".tsx" : base + ".ts"); }
    return require(name);
  }
  const code = ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX } }).outputText;
  vm.runInNewContext(code, { module, exports: module.exports, require: local, Error, Date, Intl, URLSearchParams, AbortController }); return module.exports;
}
const service = load(path.join(src, "services/assessments.ts"));
const state = load(path.join(src, "features/assessments/form-state.ts"));
const { assessmentLoad } = load(path.join(src, "features/assessments/load.ts"));
const { ReadinessView, AttemptHistoryView, CoverageView } = load(path.join(src, "features/assessments/assessment-views.tsx"));
const render = (component, props) => renderToStaticMarkup(React.createElement(component, props));
assert.equal(state.assessmentInstant("2026-10-09T09:30", "America/Los_Angeles"), "2026-10-09T16:30:00.000Z");
assert.equal(state.assessmentLocal("2026-10-09T00:00:00Z", "America/Los_Angeles"), "2026-10-08T17:00");
const preciseScheduled = "2026-10-09T00:00:23.456Z";
assert.equal(state.assessmentEditedInstant("2026-10-08T17:00", "America/Los_Angeles", preciseScheduled), preciseScheduled, "Untouched scheduled time retains seconds and milliseconds");
assert.equal(state.assessmentEditedInstant("2026-10-08T17:01", "America/Los_Angeles", preciseScheduled), "2026-10-09T00:01:00.000Z");
assert.equal(state.assessmentEditedInstant("", "America/Los_Angeles", preciseScheduled), null);
const folded = { started_at: "2026-11-01T01:30:22.456-07:00", completed_at: "2026-11-01T01:30:33.789-08:00" };
assert.equal(state.assessmentEditedInstant("2026-11-01T01:30", "America/Los_Angeles", folded.completed_at), folded.completed_at, "Untouched repeated-hour instant remains editable");
assert.throws(() => state.assessmentEditedInstant("2026-11-01T01:31", "America/Los_Angeles", folded.completed_at), /occurs twice/, "A newly selected ambiguous time still requires correction");
const preservedFold = state.attemptInput({ started: "2026-11-01T01:30", completed: "2026-11-01T01:30", score: "", maximum: "", notes: "Corrected note" }, "America/Los_Angeles", folded);
assert.equal(preservedFold.started_at, folded.started_at); assert.equal(preservedFold.completed_at, folded.completed_at);
const offsetOriginal = { started_at: "2026-10-09T09:00:45.123+08:00", completed_at: "2026-10-09T02:00:12.456Z" };
const offsetPreserved = state.attemptInput({ started: "2026-10-09T09:00", completed: "2026-10-09T10:00", score: "", maximum: "", notes: "Updated" }, "Asia/Manila", offsetOriginal);
assert.equal(offsetPreserved.started_at, offsetOriginal.started_at); assert.equal(offsetPreserved.completed_at, offsetOriginal.completed_at);
assert.throws(() => state.attemptInput({ started: "2026-10-09T09:30", completed: "2026-10-09T09:00", score: "", maximum: "", notes: "" }, "Asia/Manila", { started_at: "2026-10-09T01:30:00Z", completed_at: "2026-10-09T09:00:00+08:00" }), /Completion cannot be before/, "Ordering compares instants even with different ISO offsets");
const unscored = state.attemptInput({ started: "", completed: "", score: "", maximum: "", notes: " draft " }, "Asia/Manila");
assert.equal(unscored.score, null); assert.equal(unscored.max_score, null); assert.equal(unscored.completed_at, null);
const scored = state.attemptInput({ started: "", completed: "2026-10-09T09:00", score: "8.5", maximum: "10", notes: "" }, "Asia/Manila");
assert.equal(scored.score, 8.5); assert.equal(typeof scored.max_score, "number"); assert(!("percentage" in scored));
for (const pair of [["5", ""], ["11", "10"], ["NaN", "10"], ["0", "0"]]) assert.throws(() => state.attemptInput({ started: "", completed: "2026-10-09T09:00", score: pair[0], maximum: pair[1], notes: "" }, "Asia/Manila"));
assert.throws(() => state.attemptInput({ started: "", completed: "", score: "1", maximum: "2", notes: "" }, "Asia/Manila"));
assert.throws(() => state.attemptInput({ started: "2026-10-09T10:00", completed: "2026-10-09T09:00", score: "", maximum: "", notes: "" }, "Asia/Manila"));
const topics = [{ id: "a", subject_id: "s" }, { id: "b", subject_id: "other" }];
assert.equal(JSON.stringify(state.wholeSubjectCoverage(["b", "a"], "s", topics)), '["b"]');
const readiness = { topic_count: 0, total_videos: 0, completed_videos: 0, video_completion_percentage: null, quiz_graded_answers: 0, quiz_correct_answers: 0, quiz_accuracy_percentage: null, active_flashcards: 0, reviewed_flashcards: 0, due_flashcards: 0, overdue_flashcards: 0, as_of: "2026-10-09T00:00:00Z", timezone: "America/Los_Angeles" };
const empty = render(ReadinessView, { readiness });
assert(empty.includes("No covered videos") && empty.includes("No graded quiz answers") && !empty.includes("0%"));
assert(empty.includes("Oct 8, 2026, 5:00 PM") && empty.includes("Repeat attempts") && empty.includes("Reviewed does not mean mastered"));
const measured = render(ReadinessView, { readiness: { ...readiness, topic_count: 2, total_videos: 4, completed_videos: 3, video_completion_percentage: 75, quiz_graded_answers: 10, quiz_correct_answers: 8, quiz_accuracy_percentage: 80 } });
assert(measured.includes("75%") && measured.includes("80%") && measured.includes("3 / 4"));
const attempt = { id: "a", score: null, max_score: null, percentage: null, started_at: null, completed_at: null, created_at: readiness.as_of, notes: "<script>note</script>" };
const history = render(AttemptHistoryView, { attempts: [attempt], timezone: readiness.timezone, archived: true, edit() {} });
assert(history.includes("Unscored") && history.includes("&lt;script&gt;note&lt;/script&gt;") && !history.includes("Edit result"));
assert(render(AttemptHistoryView, { attempts: [], timezone: "Asia/Manila", archived: false, edit() {} }).includes("No results recorded"));
assert(render(CoverageView, { assessment: { coverage_subjects: [{ id: "s", code: "FAR", name: "Financial", scope: "all_topics" }], coverage_topics: [], topic_count: 5 } }).includes("All topics"));
assert(!service.assessmentError(new ApiError("PRIVATE", 422)).includes("PRIVATE"));
const { AssessmentEditor } = load(path.join(src, "features/assessments/assessment-editor.tsx"));
const { AttemptEditor } = load(path.join(src, "features/assessments/attempt-editor.tsx"));
const { AssessmentListPage } = load(path.join(src, "features/assessments/assessment-list.tsx"));
const { AssessmentDetailPage } = load(path.join(src, "features/assessments/assessment-detail.tsx"));
const definition = { id: "definition", title: "Synthetic <script>assessment</script>", description: "Test coverage", scheduled_at: "2026-10-09T00:00:00Z", status: "planned", subject_ids: ["s"], topic_ids: [], coverage_subjects: [{ id: "s", code: "FAR", name: "Financial", scope: "all_topics" }], coverage_topics: [], topic_count: 1, readiness };
loadOverrides = [{ data: { subjects: [{ id: "s", code: "FAR", name: "Financial" }], topics: [{ id: "t", subject_id: "s", title: "Synthetic topic" }] } }];
const editor = render(AssessmentEditor, { assessment: definition, timezone: readiness.timezone, close() {}, saved() {} });
assert(editor.includes('<dialog') && editor.includes('type="radio"') && editor.includes("Select topics") && editor.includes('value="2026-10-08T17:00"'));
assert(!editor.includes('type="checkbox"'), "Whole-subject selection must hide individual topic selection");
loadOverrides = [{ data: { subjects: [{ id: "s", code: "FAR", name: "Financial" }], topics: [{ id: "t", subject_id: "s", title: "Synthetic topic" }] } }];
const specific = render(AssessmentEditor, { assessment: { ...definition, subject_ids: [], topic_ids: ["t"] }, timezone: readiness.timezone, close() {}, saved() {} });
assert(specific.includes('type="checkbox" checked=""') && specific.includes("Synthetic topic"));
loadOverrides = [{ error: "Coverage options unavailable" }];
const failedEditor = render(AssessmentEditor, { timezone: "Asia/Manila", close() {}, saved() {} });
assert(failedEditor.includes("Coverage options unavailable") && failedEditor.includes('disabled="">Save assessment'));
loadOverrides = null;
const resultEditor = render(AttemptEditor, { assessmentId: "definition", attempt: { ...attempt, score: 0, max_score: 10 }, timezone: "Asia/Manila", close() {}, saved() {} });
assert(resultEditor.includes('value="0"') && resultEditor.includes("Save result") && resultEditor.includes("Asia/Manila"));
const filters = { q: "", status: "all", offset: 0 };
stateOverrides = [filters, "", false]; stateIndex = 0;
loadOverrides = [{ data: { timezone: readiness.timezone } }, { data: { assessments: [definition], total: 1, filters } }];
const listing = render(AssessmentListPage, {});
assert(listing.includes("&lt;script&gt;assessment&lt;/script&gt;") && listing.includes("Oct 8, 2026, 5:00 PM") && listing.includes("FAR (all topics)"));
stateIndex = 0; loadOverrides = [{ loading: true }, { data: { assessments: [], total: 0, filters } }];
const loadingTimezone = render(AssessmentListPage, {});
assert(loadingTimezone.includes('disabled="">New assessment') && loadingTimezone.includes("No assessments match this view"));
stateIndex = 0; loadOverrides = [{ data: { timezone: "Asia/Manila" } }, { loading: true, data: { assessments: [definition], total: 1, filters } }];
assert(!render(AssessmentListPage, {}).includes("Synthetic"), "Do not present stale list data during refresh");
stateOverrides = null;
loadOverrides = [{ data: { ...definition, status: "archived" } }, { data: { attempts: [attempt], total: 1, offset: 0 } }];
const archivedDetail = render(AssessmentDetailPage, { id: definition.id });
assert(archivedDetail.includes("Result history") && archivedDetail.includes("Unscored") && !archivedDetail.includes("Record result") && !archivedDetail.includes("Edit assessment") && !archivedDetail.includes("Edit result"));
loadOverrides = [{ data: definition }, { error: "Result history unavailable" }];
const failedHistory = render(AssessmentDetailPage, { id: definition.id });
assert(failedHistory.includes("Result history unavailable") && failedHistory.includes("Try again") && !failedHistory.includes("No results recorded"));
loadOverrides = null;
(async () => {
  await assert.rejects(assessmentLoad(Promise.reject(new ApiError("PRIVATE", 404))), (error) => error.status === 500 && error.message.includes("assessment") && !error.message.includes("quiz"));
  await service.getAssessments({ q: "cash & notes", status: "archived", offset: 20, limit: 20 });
  assert(calls.at(-1)[1].includes("q=cash+%26+notes") && calls.at(-1)[1].includes("status=archived"));
  await service.createAttempt("a/b", scored); assert.equal(calls.at(-1)[1], "/api/assessments/a%2Fb/attempts"); assert.equal(calls.at(-1)[2].score, 8.5);
  await service.updateAttempt("result", unscored); assert.equal(calls.at(-1)[0], "Patch"); assert.equal(calls.at(-1)[1], "/api/assessment-attempts/result");
  await service.archiveAssessment("definition"); assert.equal(calls.at(-1)[0], "Delete");
  console.log("PASS: assessment API, coverage, numeric result validation, profile timezone, transparent readiness and retained unscored history");
})().catch((error) => { console.error(error); process.exitCode = 1; });
