const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const ts = require("typescript");
const src = path.join(__dirname, "../src"), modules = new Map(), calls = [];
let overrides = null, stateIndex = 0;
let loadOverrides = null, authOwner = "11111111-1111-4111-8111-111111111111";
class ApiError extends Error { constructor(message, status) { super(message); this.status = status; } }
const api = { ApiError, authenticatedGet: async (...args) => { calls.push(["GET", ...args]); return {}; }, authenticatedPost: async (...args) => { calls.push(["POST", ...args]); return {}; }, authenticatedPatch: async (...args) => { calls.push(["PATCH", ...args]); return {}; }, authenticatedDelete: async (...args) => { calls.push(["DELETE", ...args]); } };
function load(file) {
  if (modules.has(file)) return modules.get(file).exports;
  const output = { exports: {} }; modules.set(file, output);
  function local(name) {
    if (name === "react") return { ...React, useState: (initial) => overrides ? [overrides[stateIndex++], () => {}] : React.useState(initial) };
    if (name === "next/link") return { default: ({ children, ...props }) => React.createElement("a", props, children) };
    if (name === "next/navigation") return { useRouter: () => ({ push() {}, replace() {} }) };
    if (name === "@/services/api" || name === "./api") return api;
    if (name === "@/features/auth/auth-provider") return { useAuth: () => ({ user: authOwner ? { id: authOwner } : null }) };
    if (name === "@/features/quizzes/shared") {
      const shared = load(path.join(src, "features/quizzes/shared.tsx"));
      return { ...shared, useQuizLoad: (...args) => loadOverrides ? { data: loadOverrides.shift() ?? null, loading: false, error: null, retry() {} } : shared.useQuizLoad(...args) };
    }
    if (name.startsWith("@/") || name.startsWith(".")) { const base = name.startsWith("@/") ? path.join(src, name.slice(2)) : path.resolve(path.dirname(file), name); return load(fs.existsSync(base + ".tsx") ? base + ".tsx" : base + ".ts"); }
    return require(name);
  }
  const code = ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017, jsx: ts.JsxEmit.ReactJSX } }).outputText;
  vm.runInNewContext(code, { module: output, exports: output.exports, require: local, Error, Date, Intl, FormData, URLSearchParams, AbortController });
  return output.exports;
}
const service = load(path.join(src, "services/flashcards.ts"));
const state = load(path.join(src, "features/flashcards/review-state.ts"));
const { RecallCardView, RecallSummary, RecallPage } = load(path.join(src, "features/flashcards/recall.tsx"));
const { CardEditor } = load(path.join(src, "features/flashcards/card-editor.tsx"));
const { DeckEditor } = load(path.join(src, "features/flashcards/deck-editor.tsx"));
const { CardHistoryView } = load(path.join(src, "features/flashcards/card-history.tsx"));
const { FlashcardLibrary } = load(path.join(src, "features/flashcards/flashcard-library.tsx"));
const card = { id: "card1", deck_id: null, subject_id: null, topic_id: null, resource_id: "resource1", source_page: 3, front: "Synthetic <script>front</script>", back: "SYNTHETIC_BACK", notes: "Synthetic note", status: "active", interval_days: 1, next_review_at: "2026-10-09T00:00:00Z", review_revision: 2, created_at: "2026-10-09T00:00:00Z", updated_at: "2026-10-09T00:00:00Z" };
const review = { id: "review1", flashcard_id: "card1", request_id: "11111111-1111-4111-8111-111111111111", previous_revision: 2, reviewed_at: "2026-10-09T00:00:00Z", rating: "good", previous_interval_days: 1, next_interval_days: 3, next_review_at: "2026-10-12T00:00:00Z", algorithm_version: "v1", front_snapshot: "Original front", back_snapshot: "Original back", created_at: "2026-10-09T00:00:00Z" };
const render = (component, props = {}) => renderToStaticMarkup(React.createElement(component, props));
const unrevealed = render(RecallCardView, { card, revealed: false, busy: false, pending: null, reveal() {}, rate() {}, timezone: "Asia/Manila", allowReview: true });
assert(unrevealed.includes("Reveal answer") && unrevealed.includes("&lt;script&gt;front&lt;/script&gt;"));
assert(!unrevealed.includes("SYNTHETIC_BACK") && !unrevealed.includes(">Good<"), "Answer and rating controls must wait for reveal");
const revealed = render(RecallCardView, { card, revealed: true, busy: false, pending: null, reveal() {}, rate() {}, timezone: "Asia/Manila", allowReview: true });
for (const label of ["SYNTHETIC_BACK", ">Again<", ">Hard<", ">Good<", ">Easy<"]) assert(revealed.includes(label));
const pending = state.pendingReview(card, "good", () => review.request_id);
const recovery = load(path.join(src, "features/flashcards/review-recovery.ts"));
const stored = new Map();
const storage = { getItem: (key) => stored.get(key) ?? null, setItem: (key, value) => stored.set(key, value), removeItem: (key) => stored.delete(key) };
const owner = "11111111-1111-4111-8111-111111111111";
const recoverable = { ...pending, card: { ...card, id: "22222222-2222-4222-8222-222222222222" } };
assert.equal(recovery.rememberReview(storage, owner, recoverable), true);
const restored = recovery.readReviewRecovery(storage, owner);
assert.equal(restored.metadata.request_id, review.request_id);
assert.equal(restored.metadata.expected_revision, card.review_revision);
assert.equal(restored.metadata.rating, "good");
assert.equal(Object.keys(restored.metadata).length, 4);
assert(![...stored.values()][0].includes(card.front) && ![...stored.values()][0].includes(card.back), "Recovery must not store private card text");
assert.equal(recovery.readReviewRecovery(storage, "other-owner").metadata, null, "Recovery must be owner-scoped");
recovery.clearReviewRecovery(storage, owner);
assert.equal(recovery.readReviewRecovery(storage, owner).metadata, null);
storage.setItem(`study-hub:recall-review:${owner}`, JSON.stringify({ ...restored.metadata, front: "PRIVATE" }));
assert.equal(recovery.readReviewRecovery(storage, owner).metadata, null, "Unexpected private fields invalidate recovery");
assert.equal(stored.size, 0);
storage.setItem(`study-hub:recall-review:${owner}`, "malformed");
assert.equal(recovery.readReviewRecovery(storage, owner).metadata, null);
assert.equal(recovery.readReviewRecovery(null, owner).available, false);
assert.equal(recovery.rememberReview({ setItem() { throw Error("denied"); } }, owner, recoverable), false);
assert.equal(JSON.stringify(Object.keys(pending.body).sort()), '["expected_revision","rating","request_id"]');
assert.equal(pending.body.expected_revision, 2); assert.equal(pending.body.request_id, review.request_id);
const retry = render(RecallCardView, { card, revealed: true, busy: false, pending, reveal() {}, rate() {}, timezone: "Asia/Manila", allowReview: true });
assert(retry.includes("Retry Good") && retry.includes("SYNTHETIC_BACK") && !retry.includes(">Easy<"), "Failed reviews must preserve revealed card and original rating");
const upcoming = render(RecallCardView, { card, revealed: true, busy: false, pending: null, reveal() {}, rate() {}, timezone: "Asia/Manila", allowReview: false });
assert(!upcoming.includes(">Good<") && upcoming.includes("not due"), "Upcoming cards cannot be rated early");
const summary = render(RecallSummary, { summary: { overdue: 4, due_today: 3, upcoming: 9 }, timezone: "America/Los_Angeles", asOf: card.next_review_at });
assert(summary.includes("<dt>Overdue</dt><dd>4</dd>") && summary.includes("<dt>Due today</dt><dd>3</dd>") && summary.includes("<dt>Upcoming</dt><dd>9</dd>") && summary.includes("America/Los_Angeles") && summary.includes("Oct 8, 2026, 5:00 PM"));
const editor = render(CardEditor, { close() {}, saved() {} });
assert(editor.includes("<dialog") && editor.includes('maxLength="5000"') && editor.includes('maxLength="12000"') && editor.includes("Save flashcard"));
assert(render(DeckEditor, { close() {}, saved() {} }).includes("Save deck"));
const history = render(CardHistoryView, { reviews: [review], timezone: "America/Los_Angeles" });
assert(history.includes("Original front") && history.includes("Original back") && history.includes("Oct 8, 2026, 5:00 PM") && history.includes("3 days"));
assert(render(FlashcardLibrary).includes("Flashcards") && render(FlashcardLibrary).includes("All statuses") && render(FlashcardLibrary).includes("New deck"));
assert(render(RecallPage).includes("Recall") && render(RecallPage).includes("Upcoming"));
assert.equal(RecallPage().key, authOwner, "Switching account must remount all private recall state");
authOwner = null;
assert.equal(render(RecallPage), "", "No recall content renders without the shared authenticated identity");
authOwner = owner;
loadOverrides = [[], { cards: [], total: 0, filters: { offset: 0 } }, { decks: [], total: 0, filters: { offset: 0 } }, { decks: [], total: 0 }];
const emptyLibrary = render(FlashcardLibrary);
assert(emptyLibrary.includes("No cards match this view") && emptyLibrary.includes("No decks match this view"));
loadOverrides = [[], { cards: [], total: 0, filters: { offset: 0 }, summary: { overdue: 0, due_today: 0, upcoming: 0 }, timezone: "Asia/Manila", as_of: card.next_review_at }, { decks: [], total: 0 }];
assert(render(RecallPage).includes("No cards remain in this loaded view"));
loadOverrides = null;
assert(render(CardHistoryView, { reviews: [], timezone: "Asia/Manila" }).includes("No reviews yet"));
const question = { prompt: "Synthetic mistake", correct_keys: ["C", "A"], options: [{ key: "A", text: "First answer" }, { key: "B", text: "Wrong" }, { key: "C", text: "Third answer" }], explanation: "Synthetic reason", subject_id: "subject", topic_id: "topic", resource_id: "resource", source_page: 2 };
const draft = state.cardFromMistake(question);
assert.equal(draft.front, question.prompt); assert.equal(draft.back, "First answer\nThird answer\n\nSynthetic reason");
assert.equal(draft.resource_id, "resource"); assert.equal(draft.source_page, 2); assert(!JSON.stringify(draft).includes("correct_keys"));
assert(service.flashcardError(new ApiError("SECRET", 409)).includes("changed") && !service.flashcardError(new ApiError("SECRET", 422)).includes("SECRET"));
(async () => {
  const accepted = [];
  await assert.rejects(state.confirmReview(pending, async () => { throw new Error("offline"); }, (value) => accepted.push(value)));
  assert.equal(accepted.length, 0, "Failed review must not advance or clear the pending request");
  assert.equal(pending.body.request_id, review.request_id); assert.equal(pending.card.review_revision, 2);
  await state.confirmReview(pending, async (id, body) => { assert.equal(id, card.id); assert.equal(body, pending.body); return review; }, (value) => accepted.push(value));
  assert.equal(accepted[0], review);
  await service.reviewCard(card.id, pending.body);
  assert.equal(calls.at(-1)[1], "/api/flashcards/card1/review"); assert.equal(JSON.stringify(calls.at(-1)[2]), JSON.stringify(pending.body));
  await service.getDueCards({ mode: "upcoming", deck_id: "deck", limit: 20, offset: 20 });
  assert(calls.at(-1)[1].includes("mode=upcoming") && calls.at(-1)[1].includes("offset=20"));
  await service.getCards({ status: "all", q: "cash & notes" }); assert(calls.at(-1)[1].includes("status=all") && calls.at(-1)[1].includes("q=cash+%26+notes"));
  await service.archiveCard("card1"); assert.equal(calls.at(-1)[0], "DELETE");
  await service.archiveDeck("deck1"); assert.equal(calls.at(-1)[1], "/api/flashcard-decks/deck1");
  console.log("PASS: flashcard services, reveal protection, retry identity, server-confirmed progression, profile timezone and manual mistake mapping");
})().catch((error) => { console.error(error); process.exitCode = 1; });
