const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const ts = require("typescript");
const src = path.join(__dirname, "../src");
const modules = new Map();
let overrides = null, stateIndex = 0;
const calls = [];
class ApiError extends Error { constructor(message, status) { super(message); this.status = status; } }
const api = { ApiError, authenticatedGet: async (...args) => { calls.push(["GET", ...args]); return {}; }, authenticatedPost: async (...args) => { calls.push(["POST", ...args]); return {}; }, authenticatedPatch: async (...args) => { calls.push(["PATCH", ...args]); return {}; } };
function load(file) {
  if (modules.has(file)) return modules.get(file).exports;
  const output = { exports: {} }; modules.set(file, output);
  function local(name) {
    if (name === "react") return { ...React, useState: (initial) => overrides ? [overrides[stateIndex++], () => {}] : React.useState(initial) };
    if (name === "next/link") return { default: ({ children, ...props }) => React.createElement("a", props, children) };
    if (name === "next/navigation") return { useRouter: () => ({ push() {}, replace() {} }) };
    if (name === "@/services/api" || name === "./api") return api;
    if (name.startsWith("@/") || name.startsWith(".")) { const base = name.startsWith("@/") ? path.join(src, name.slice(2)) : path.resolve(path.dirname(file), name); return load(fs.existsSync(base + ".tsx") ? base + ".tsx" : base + ".ts"); }
    return require(name);
  }
  const code = ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017, jsx: ts.JsxEmit.ReactJSX } }).outputText;
  vm.runInNewContext(code, { module: output, exports: output.exports, require: local, Error, Date, FormData, URLSearchParams, AbortController });
  return output.exports;
}
const service = load(path.join(src, "services/quizzes.ts"));
const { AttemptQuestionView, QuizAttemptPage } = load(path.join(src, "features/quizzes/quiz-attempt.tsx"));
const { persistBeforeAction, reviewQuestion } = load(path.join(src, "features/quizzes/attempt-state.ts"));
const recovery = load(path.join(src, "features/quizzes/draft-recovery.ts"));
const { QuizListPage, quizTimestamp } = load(path.join(src, "features/quizzes/quiz-list.tsx"));
const { QuestionBank } = load(path.join(src, "features/quizzes/question-bank.tsx"));
const { QuestionEditor, nextOptionKey } = load(path.join(src, "features/quizzes/question-editor.tsx"));
const { QuestionImport } = load(path.join(src, "features/quizzes/question-import.tsx"));
const { QuizBuilder } = load(path.join(src, "features/quizzes/quiz-builder.tsx"));
const question = { id: "q1", prompt: "Synthetic <script>question</script>", question_type: "single_select", subject_id: null, topic_id: null, resource_id: "source1", source_page: 2, options: [{ key: "A", text: "Synthetic first" }, { key: "B", text: "Synthetic second" }], selected_keys: ["B"], correct_keys: ["A"], explanation: "PRIVATE_EXPLANATION", is_correct: false };
const attempt = { id: "a1", quiz_id: "quiz1", title: "Synthetic quiz", status: "in_progress", started_at: "2026-10-09T00:00:00Z", completed_at: null, score_value: null, total_questions: 1, score_percent: null, questions: [question] };
const render = (component, props) => renderToStaticMarkup(React.createElement(component, props));
const taking = render(AttemptQuestionView, { attempt, question, selected: ["B"], change() {}, busy: false });
assert(taking.includes('type="radio"') && taking.includes("&lt;script&gt;question&lt;/script&gt;"));
assert(!taking.includes("PRIVATE_EXPLANATION") && !taking.includes("Correct answer") && !taking.includes("data-result="), "Answer-key projection must remain hidden before completion, even on an unexpected payload");
assert.equal(reviewQuestion(attempt, question), null);
const review = render(AttemptQuestionView, { attempt: { ...attempt, status: "completed" }, question, selected: ["B"], change() {}, busy: false });
assert(/<dt>Correct answer:<\/dt><dd>A<\/dd>/.test(review) && review.includes("PRIVATE_EXPLANATION") && review.includes("Incorrect") && review.includes("disabled="));
assert(review.includes('href="/library/source1"') && review.includes("Page 2"));
assert(render(AttemptQuestionView, { attempt, question: { ...question, question_type: "multi_select" }, selected: [], change() {}, busy: false }).includes('type="checkbox"'));
assert(render(QuizAttemptPage, { attemptId: "a1" }).includes('role="status"'));
function withStates(component, props, states) { overrides = states; stateIndex = 0; try { return render(component, props); } finally { overrides = null; } }
const failedSave = withStates(QuizAttemptPage, { attemptId: "a1" }, [attempt, false, "Refresh failed", 0, 0, ["A"], false, "Save failed", false]);
assert(failedSave.includes("Refresh failed") && failedSave.includes("Save failed") && failedSave.includes("Unsaved answer") && failedSave.includes("Synthetic first"));
assert(!failedSave.includes("Answer saved") && !failedSave.includes("PRIVATE_EXPLANATION"), "A failed write retains draft and never reports saved or reveals grading");
const completed = withStates(QuizAttemptPage, { attemptId: "a1" }, [{ ...attempt, status: "completed", score_value: 0, score_percent: 0 }, false, null, 0, 0, ["B"], false, null, false]);
assert(completed.includes("0%") && completed.includes("0 correct out of 1") && /<dt>Correct answer:<\/dt><dd>A<\/dd>/.test(completed) && !completed.includes("Submit quiz"));
const restored = withStates(QuizAttemptPage, { attemptId: "a1" }, [attempt, false, null, 0, 0, ["A"], false, null, false, true]);
assert(restored.includes("Unsaved answer restored") && restored.includes("Unsaved answer"));
const noRecovery = withStates(QuizAttemptPage, { attemptId: "a1" }, [attempt, false, null, 0, 0, ["A"], false, null, false, false, true]);
assert(noRecovery.includes("Browser draft recovery is unavailable. Save your answer before leaving this page.") && !noRecovery.includes("Unsaved answer restored"));
assert(render(QuizListPage).includes("New quiz") && render(QuizListPage).includes("Attempt history"));
assert(quizTimestamp(attempt.started_at, "America/Los_Angeles").includes("Oct 8, 2026") && quizTimestamp(attempt.started_at, "America/Los_Angeles").includes("5:00 PM"), "Quiz timestamps must use the profile's timezone, including the prior local date");
const profileHistory = withStates(QuizListPage, {}, [{ subject_id: "", q: "", offset: 0 }, "", 0, "America/Los_Angeles", false, 0, [], false, null, 0, { quizzes: [], total: 0, filters: { offset: 0 } }, false, null, 0, { attempts: [attempt], total: 1, offset: 0 }, false, null, 0]);
assert(profileHistory.includes("Dates use America/Los_Angeles.") && profileHistory.includes("Oct 8, 2026, 5:00 PM"));
const fallbackHistory = withStates(QuizListPage, {}, [{ subject_id: "", q: "", offset: 0 }, "", 0, null, true, 0, [], false, null, 0, { quizzes: [], total: 0, filters: { offset: 0 } }, false, null, 0, { attempts: [attempt], total: 1, offset: 0 }, false, null, 0]);
assert(fallbackHistory.includes("Dates use Asia/Manila until your profile timezone is available.") && fallbackHistory.includes("Retry timezone") && fallbackHistory.includes("Oct 9, 2026, 8:00 AM"));
assert(render(QuestionBank).includes("Import CSV") && render(QuestionBank).includes("All types"));
const bankRetained = withStates(QuestionBank, {}, [{ q: "", subject_id: "", question_type: "", offset: 0 }, "", null, false, null, false, null, null, [], false, null, 0, { questions: [{ ...question, origin: "manual", is_archived: false }], total: 1, offset: 0, filters: {} }, false, "Bank refresh failed", 0]);
assert(bankRetained.includes("Bank refresh failed") && bankRetained.includes("Synthetic first") === false && bankRetained.includes("Synthetic &lt;script&gt;question"));
const editor = render(QuestionEditor, { close() {}, saved() {} });
assert(editor.includes("<dialog") && editor.includes("Mark A correct") && editor.includes('maxLength="5000"') && editor.includes("PDF page (optional)"));
assert.equal(nextOptionKey([{ key: "A" }, { key: "C" }]), "B", "Sparse choices must use the first unused key");
assert.equal(nextOptionKey([{ key: "F" }, { key: "B" }, { key: "A" }]), "C", "Out-of-order choices must not duplicate a key");
assert.equal(nextOptionKey([..."ABCDEF"].map((key) => ({ key }))), undefined, "Full choices must disallow another option");
const importing = render(QuestionImport, { close() {}, saved() {} });
assert(importing.includes("Preview CSV") && importing.includes("1 MiB") && !importing.includes("Confirm import"));
const blockedImport = withStates(QuestionImport, { close() {}, saved() {} }, [{ name: "synthetic.csv", size: 12 }, { row_count: 2, valid_count: 1, duplicate_count: 0, proposed_inserts: 1, unchanged: 0, warnings: [], errors: [{ row: 2, field: "correct_answer", message: "Unknown key" }], sample: [], preview_token: null }, false, null]);
assert(blockedImport.includes("Errors block all imports") && blockedImport.includes("Row 2") && blockedImport.includes("Unknown key"));
assert(/disabled=""[^>]*>Confirm import/.test(blockedImport), "Preview errors must disable commit");
assert(render(QuizBuilder).includes("Quiz order") && render(QuizBuilder).includes("Save and start"));
assert.equal(service.questionCsvError({ name: "questions.csv", size: 1048576 }), null);
assert(service.questionCsvError({ name: "questions.csv", size: 1048577 }).includes("1 MiB"));
assert(service.questionCsvError({ name: "questions.xlsx", size: 10 }).includes("CSV"));
assert(!service.quizError(new ApiError("SECRET_PROVIDER", 422)).includes("SECRET_PROVIDER"));
const records = new Map();
const storage = { getItem: (key) => records.get(key) ?? null, setItem: (key, value) => records.set(key, value), removeItem: (key) => records.delete(key) };
const secondQuestion = { ...question, id: "q2", selected_keys: [], question_type: "multi_select" };
const recoveringAttempt = { ...attempt, questions: [question, secondQuestion], total_questions: 2 };
assert.equal(recovery.rememberAttemptDraft(storage, recoveringAttempt, secondQuestion, ["B", "A"]), true);
assert.equal(records.size, 1, "Draft is backed up synchronously before navigation");
const record = [...records.values()][0];
assert.equal(JSON.stringify(Object.keys(JSON.parse(record)).sort()), '["baseline_keys","question_id","selected_keys"]');
assert(!record.includes("PRIVATE_EXPLANATION") && !record.includes("Synthetic"), "Recovery must contain no prompt, grading keys, explanation or token");
const recovered = recovery.restoreAttemptDraft(storage, recoveringAttempt);
assert.equal(recovered.index, 1); assert.equal(recovered.question_id, "q2"); assert.equal(JSON.stringify(recovered.selected_keys), '["B","A"]');
recovery.clearConfirmedDraft(storage, recoveringAttempt);
assert.equal(records.size, 1, "An unchanged server response must not clear an unsaved draft");
recovery.clearConfirmedDraft(storage, { ...recoveringAttempt, questions: [question, { ...secondQuestion, selected_keys: ["A", "B"] }] });
assert.equal(records.size, 0, "Successful matching answer save clears its recovery record");
recovery.rememberAttemptDraft(storage, recoveringAttempt, secondQuestion, ["A"]);
assert.equal(recovery.restoreAttemptDraft(storage, { ...recoveringAttempt, questions: [question, { ...secondQuestion, selected_keys: ["B"] }] }), null);
assert.equal(records.size, 0, "A changed server baseline must win over an old draft");
recovery.rememberAttemptDraft(storage, recoveringAttempt, secondQuestion, ["SECRET_UNKNOWN"]);
assert.equal(records.size, 0, "Unknown selections cannot be backed up");
storage.setItem("study-hub:quiz-draft:a1", JSON.stringify({ question_id: "q2", selected_keys: ["A", "A"], baseline_keys: [] }));
assert.equal(recovery.restoreAttemptDraft(storage, recoveringAttempt), null);
assert.equal(records.size, 0, "Duplicate or invalid recovery selections must be discarded");
storage.setItem("study-hub:quiz-draft:a1", JSON.stringify({ question_id: "missing", selected_keys: ["A"], baseline_keys: [] }));
assert.equal(recovery.restoreAttemptDraft(storage, recoveringAttempt), null);
recovery.rememberAttemptDraft(storage, recoveringAttempt, secondQuestion, ["A"]);
assert.equal(recovery.restoreAttemptDraft(storage, { ...recoveringAttempt, status: "completed" }), null);
assert.equal(records.size, 0, "Completion clears the attempt's recovery state");
recovery.rememberAttemptDraft(storage, attempt, question, []);
recovery.rememberAttemptDraft(storage, attempt, question, question.selected_keys);
assert.equal(records.size, 0, "Returning to the saved answer clears the draft");
const deniedStorage = { getItem() { throw new Error("denied"); }, setItem() { throw new Error("denied"); }, removeItem() { throw new Error("denied"); } };
assert.equal(recovery.rememberAttemptDraft(deniedStorage, attempt, question, []), false, "Denied setItem must report unavailable backup");
assert.equal(recovery.rememberAttemptDraft(null, attempt, question, []), false, "Missing session storage must report unavailable backup");
assert.equal(recovery.rememberAttemptDraft(null, attempt, question, question.selected_keys), true, "A saved answer needs no recovery backup");
assert.equal(recovery.restoreAttemptDraft(deniedStorage, attempt), null);
(async () => {
  const accepted = [], actions = [];
  await assert.rejects(persistBeforeAction(async () => { throw new Error("save failed"); }, (value) => accepted.push(value), (value) => actions.push(value)));
  assert.equal(accepted.length, 0); assert.equal(actions.length, 0, "Failed answer saves must prevent navigation and submit");
  await persistBeforeAction(async () => attempt, (value) => accepted.push(value), (value) => actions.push(value));
  assert.equal(accepted[0], attempt); assert.equal(actions[0], attempt, "Actions must use the server-confirmed attempt");
  await service.getQuestions({ q: "cash & notes", subject_id: "s1", limit: 20, offset: 20 });
  assert(calls.at(-1)[1].includes("q=cash+%26+notes") && calls.at(-1)[1].includes("offset=20"));
  await service.saveAnswer("a/1", "q1", ["A"]);
  const answerCall = calls.at(-1); assert.equal(answerCall[0], "POST"); assert.equal(answerCall[1], "/api/quiz-attempts/a%2F1/answers");
  assert.equal(JSON.stringify(answerCall[2]), JSON.stringify({ question_id: "q1", selected_keys: ["A"] }));
  await service.completeAttempt("a1"); assert.equal(calls.at(-1)[1], "/api/quiz-attempts/a1/complete");
  await service.archiveQuestion("q1"); assert.equal(JSON.stringify(calls.at(-1)[2]), '{"is_archived":true}');
  const input = { title: "Synthetic", description: null, subject_id: null, topic_id: null, question_ids: ["q2", "q1"] };
  await service.updateQuiz("quiz1", input); assert.equal(JSON.stringify(calls.at(-1)[2].question_ids), '["q2","q1"]', "Question order must reach FastAPI unchanged");
  const file = new Blob(["question,correct_answer\nSynthetic,A\n"], { type: "text/csv" });
  await service.previewQuestions(file); assert(calls.at(-1)[2] instanceof FormData && calls.at(-1)[2].has("file") && !calls.at(-1)[2].has("preview_token"));
  await service.commitQuestions(file, "synthetic-token"); assert.equal(calls.at(-1)[2].get("preview_token"), "synthetic-token");
  console.log("PASS: quiz service contracts, answer protection, persisted navigation, retained errors, editor/import and review states");
})().catch((error) => { console.error(error); process.exitCode = 1; });
